Executable: C:\Users\User\Desktop\EklipseProjects\test\build\test.exe
AssetsDirectory: C:\Users\User\Desktop\EklipseProjects\test\build\Assets
ScriptsLibrary: C:\Users\User\Desktop\EklipseProjects\test\build\test.dll
StartScene: C:\Users\User\Desktop\EklipseProjects\test\build\Assets\Scenes\Unititled.eksc