Config:
  Name: example4
  Executable: example4.exe
  AssetsDirectory: Assets
  ScriptsLibrary: example4.dll
  StartScene: Assets\Scenes\Untitled.eksc
  StartSceneHandle: 10094526034968617192
RendererSettings:
  Vsync: false
  MsaaSamplesIndex: 0